### PR TITLE
Create appveyor.yml

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@pestotoast Is it possible to install dependencies using nuget in here? If so can you please provide the necessary info? THX

**Comment by pestotoast** [comment]
@DeepDiver1975 I will take a look at this.

**Comment by pestotoast** [comment]
Yeeeha, now it works! :)

**Comment by pestotoast** [comment]
I am trying to add a status badge to the readme but the link I tried does not seem to work:
[https://ci.appveyor.com/api/projects/status/github/DeepDiver1975/ownclouduniversal](url)

Can you help?

**Comment by DeepDiver1975** [comment]
[Build status](https://ci.appveyor.com/project/DeepDiver1975/ownclouduniversal)

**Pull request merged**
